### ISSUE TITLE
Documentation fails to build with sphinx 1.7

### ISSUE THREAD

**Issue by eli-schwartz** [readthedocs/recommonmark#109]
```
$ make -C docs text
make: Entering directory '/build/python-recommonmark/src/python-recommonmark/docs'
sphinx-build -b text -d _build/doctrees   . _build/text
Running Sphinx v1.7.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [text]: targets for 3 source files that are out of date
updating environment: 3 added, 0 changed, 0 removed
/build/python-recommonmark/src/python-recommonmark/recommonmark/parser.py:63: UserWarning: Container node skipped: type=document                      
  warn("Container node skipped: type={0}".format(mdnode.t))
/build/python-recommonmark/src/python-recommonmark/recommonmark/parser.py:63: UserWarning: Container node skipped: type=document                      
  warn("Container node skipped: type={0}".format(mdnode.t))
/build/python-recommonmark/src/python-recommonmark/docs/api_ref.md:: WARNING: AutoStructify option "enable_auto_doc_ref" is deprecated
/build/python-recommonmark/src/python-recommonmark/docs/auto_structify.md:: WARNING: AutoStructify option "enable_auto_doc_ref" is deprecated
/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py:docstring of recommonmark.transform.AutoStructify:1: WARNING: duplicate object description of recommonmark.transform.AutoStructify, other instance in /build/python-recommonmark/src/python-recommonmark/docs/api_ref.md, use :noindex: for one of them

Exception occurred:
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 189, in parse
    inputstring, tab_width=document.settings.tab_width,
AttributeError: 'Values' object has no attribute 'tab_width'
The full traceback has been saved in /tmp/sphinx-err-ujicjvoe.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:136: text] Error 2
make: Leaving directory '/build/python-recommonmark/src/python-recommonmark/docs'

$ cat /tmp/sphinx-err-ujicjvoe.log
# Sphinx version: 1.7.5
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   building [text]: targets for 3 source files that are out of date
#   
#   updating environment:
#   
#   3 added, 0 changed, 0 removed
#   
#   reading sources... [ 33%] api_ref
#   
#   reading sources... [ 66%] auto_structify
#   
# Loaded extensions:
#   alabaster (0.7.11) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.7.5) from /usr/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (1.7.5) from /usr/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.mathjax (1.7.5) from /usr/lib/python3.6/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 565, in update
    self._read_serial(docnames, self.app)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 584, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 659, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/usr/lib/python3.6/site-packages/sphinx/io.py", line 294, in read_doc
    pub.publish()
  File "/usr/lib/python3.6/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/lib/python3.6/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
    Transformer.apply_transforms(self)
  File "/usr/lib/python3.6/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 328, in apply
    self.traverse(self.document)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 308, in traverse
    self.traverse(child)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 308, in traverse
    self.traverse(child)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 308, in traverse
    self.traverse(child)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 298, in traverse
    newnode = self.find_replace(c)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 280, in find_replace
    newnode = self.auto_code_block(node)
  File "/build/python-recommonmark/src/python-recommonmark/recommonmark/transform.py", line 254, in auto_code_block
    parser.parse(newsource, new_doc)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 189, in parse
    inputstring, tab_width=document.settings.tab_width,
AttributeError: 'Values' object has no attribute 'tab_width'
```
Works fine if I revert sphinx back to 1.6.5

**Comment by yan12125** [comment]
With the latest commit from the 1.7 branch of sphinx (sphinx-doc/sphinx@052f24facef46a11286260a1868c5d628894e41c), `make -C docs text` runs fine. Looks like it's fixed by https://github.com/sphinx-doc/sphinx/pull/5052.

BTW, sphinx milestone 1.7.6 is due today ;-) https://github.com/sphinx-doc/sphinx/milestone/47
