### ISSUE TITLE
ImportError: cannot import name Parser with recommonmark from the github

### ISSUE THREAD

**Issue by cyjseagull** [readthedocs/recommonmark#114]
**The latest version will cause errors as below when built in readthedocs. How can i fix it?**
**recommonmark path: https://github.com/rtfd/recommonmark**

Running Sphinx v1.6.7
making output directory...

Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 168, in init
confoverrides or {}, self.tags)
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 163, in init
raise ConfigError(CONFIG_ERROR % traceback.format_exc())
ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 157, in init
execfile_(filename, config)
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
exec_(code, globals)
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec
exec("""exec code in globs, locs""")
File "", line 1, in
File "conf.py", line 18, in
from recommonmark.parser import CommonMarkParser
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/src/recommonmark/recommonmark/parser.py", line 9, in
from CommonMark import Parser
ImportError: cannot import name Parser

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 157, in init
execfile_(filename, config)
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
exec_(code, globals)
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec
exec("""exec code in globs, locs""")
File "", line 1, in
File "conf.py", line 18, in
from recommonmark.parser import CommonMarkParser
File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/src/recommonmark/recommonmark/parser.py", line 9, in
from CommonMark import Parser
ImportError: cannot import name Parser

**Comment by cyjseagull** [comment]
I noticed that https://readthedocs.org/projects/recommonmark/builds/7270113/ has been built failed too.

**Comment by ericholscher** [comment]
The way to import this has been updated in our latest release, please try this: https://github.com/rtfd/recommonmark#getting-started
