### ISSUE TITLE
cm2html (and other scripts) break on local links

### ISSUE THREAD

**Issue by mitya57** [readthedocs/recommonmark#205]
Test case that I am able to reproduce in a freshly created virtualenv:

- `pip install recommonmark`
- `echo "[link](./bar.mkd)" > foo.mkd`
- `cm2html ./foo.mkd`

Fails with the following error:
```
/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
NotImplementedError: <class 'docutils.writers.html4css1.HTMLTranslator'> visiting unknown node type: pending_xref
Exiting due to error.  Use "--traceback" to diagnose.
```

Traceback produced with `--traceback` option:
```pytb
Traceback (most recent call last):
  File "/home/dmitry/.virtualenvs/recommonmark/bin/cm2html", line 8, in <module>
    sys.exit(cm2html())
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/recommonmark/scripts.py", line 25, in cm2html
    publish_cmdline(writer_name='html',
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/core.py", line 353, in publish_cmdline
    output = pub.publish(
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/core.py", line 220, in publish
    output = self.writer.write(self.document, self.destination)
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/writers/_html_base.py", line 78, in translate
    self.document.walkabout(visitor)
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "/home/dmitry/.virtualenvs/recommonmark/lib/python3.8/site-packages/docutils/nodes.py", line 2018, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'docutils.writers.html4css1.HTMLTranslator'> visiting unknown node type: pending_xref
```

It looks like `pending_xref` node is specific to Sphinx, but cm2html tries to use it with pure Docutils.

**Comment by notpushkin** [comment]
Temporarily commenting out this piece of code did the trick for me:

https://github.com/readthedocs/recommonmark/blob/5ec3751ed8aae194cffd84bde2e4e33e1bd5182b/recommonmark/parser.py#L176-L189

Perhaps disabling it on a configuration switch or – even better – moving to a Sphinx-specific transform (if possible) would be a nice idea.

**Comment by brechtm** [comment]
Related: #202
