### ISSUE TITLE
make html works locally, however, RTD fails to build -- any ideas?

### ISSUE THREAD

**Issue by brianjking** [readthedocs/recommonmark#29]
```
Running Sphinx v1.3.1
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dockdogs-club-handbook/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dockdogs-club-handbook/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 126, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dockdogs-club-handbook/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dockdogs-club-handbook/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dockdogs-club-handbook/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 25, in <module>
    from recommonmark.transform import AutoStructify
ImportError: No module named transform

Exception occurred:
  File "conf.py", line 25, in <module>
    from recommonmark.transform import AutoStructify
ImportError: No module named transform
The full traceback has been saved in /tmp/sphinx-err-VX3DzD.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

**Comment by ericholscher** [comment]
Yea -- this is an issue where we're installing recommonmark that depends on an old version of commonmark-py, but then the doc builds force the PATH to the local commonmark, breaking recommonmark. We shouldn't be doing this magic stuff on RTD, and it's on my list of things to fix!

**Comment by brianjking** [comment]
@ericholscher Thanks for the reply. How were you guys able to get it to build at readthedocs.org then?

**Comment by brianjking** [comment]
@ericholscher I forked the repo and was able to build it at readthedocs.org as well. So I guess my question is what am I doing wrong?

Thanks!

http://recommonmark-test.readthedocs.org/en/latest/ --> fork showing deployment.

**Comment by eafzali** [comment]
I'm having the same problem @brianjking, have you came up with a solution?

**Comment by willingc** [comment]
Hi @eafzali, I have been able to build cleanly on readthedocs by pinning the recommonmark version to 0.4 in our ``requirements.txt``

https://github.com/jupyter/jupyterhub/blob/master/docs/requirements.txt
https://github.com/jupyter/jupyterhub/blob/master/docs/source/conf.py
