### ISSUE TITLE
Cannot nest headers inside of block quotes

### ISSUE THREAD

**Issue by futuro** [readthedocs/recommonmark#57]
If you attempt to use something like the following

```
> # Header
```

Recommonmark will through the following stack trace.

```
# Sphinx version: 1.4.8
# Python version: 3.5.2 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   reading sources... [ 58%] setup_osx
#   reading sources... [ 62%] setup_ubuntu
#   reading sources... [ 65%] setup_win7
#   reading sources... [ 68%] setup_win8
#   reading sources... [ 72%] track1
#   reading sources... [ 75%] track1/Page_1_Intro_TOC
#   reading sources... [ 79%] track1/Page_2_Big_Picture
#   reading sources... [ 82%] track1/Page_3_Start_project
#   reading sources... [ 86%] track1/Page_4_Change_code
#   reading sources... [ 89%] track1/Page_5_More_code_changes
# Loaded extensions:
#   alabaster (0.7.9) from /home/user/.virt-envs/installfest/lib/python3.5/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/application.py", line 297, in build
    self.builder.build_update()
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/environment.py", line 569, in update
    self._read_serial(docnames, app)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/environment.py", line 589, in _read_serial
    self.read_doc(docname, app)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/environment.py", line 742, in read_doc
    pub.publish()
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 87, in parse
    self.convert_block(ast)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 49, in convert_block
    self.convert_blocks(block.children)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 45, in convert_blocks
    self.convert_block(block)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 55, in convert_block
    self.blockquote(block)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 139, in blockquote
    self.convert_blocks(block.children)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 45, in convert_blocks
    self.convert_block(block)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 51, in convert_block
    self.section(block)
  File "/home/user/.virt-envs/installfest/lib/python3.5/site-packages/recommonmark/parser.py", line 110, in section
    self.current_node.document.note_implicit_target(new_section, new_section)
AttributeError: 'NoneType' object has no attribute 'note_implicit_target'
```

I've tried parsing that markdown with just commonmark and it works fine, so currently this looks to be a recommonmark specific issue.

I'm not really certain how to debug this further, but if there's anything I can do to help please let me know.

Thank you.

**Comment by pfultz2** [comment]
Did you run this from the master branch? As it seemed to work fine for me when using `> # Header` in a markdown file.

**Comment by futuro** [comment]
I'm running it from pip and recommonmark is version 0.4.0.

**Comment by futuro** [comment]
This gist https://gist.github.com/futuro/71b95c34750fc69dadf306e6d8249884 contains all of the files I'm using to test this, and the command I'm running is `sphinx-build -b html -d _build/doctrees -D latex_paper_size=a4 -D latex_paper_size=letter . _build/html`

**Comment by pfultz2** [comment]
Ok, try using it from master, you should be able to install from master with `pip install git+https://github.com/rtfd/recommonmark.git` or adding `git+https://github.com/rtfd/recommonmark.git` to your requirements.txt file.

**Comment by pfultz2** [comment]
Its possible that this commit [here](https://github.com/rtfd/recommonmark/commit/40a82ef39d0aa155e1f1cddb85e6f70684a0f1ef) that fixed the problem with syntax highlighting also fixed the problem with headers in a block.

**Comment by futuro** [comment]
Pulling in master fixed the issue. I'm not certain which commit fixed it, so I'm inclined to go with your assessment :)
