### ISSUE TITLE
can not get the anchor of titles all  in  Chinese

### ISSUE THREAD

**Issue by Fusyong** [readthedocs/recommonmark#83]
Thanks to your great works, I can use Sphinx with markdown.
But I run into a problem soon, that the doc made with Sphinx and  recommonmark can not get a anchor of a **pure** Chinese title, i.e., can not navigate to the title with clicking sidebar item.  And it will work after being translated into rst file with Pandoc. e.g. in a MD file:
```
# 学习

//this one can not get its anchor 

# 学习learn

//this one works 

# learn

//this one works 
```

**Comment by fyears** [comment]
Use the latest one downloaded from github, or just:

```
pip uninstall recommonmark
pip install git+https://github.com/rtfd/recommonmark
```

**Comment by Fusyong** [comment]
Thanks

**Comment by cyjseagull** [comment]
The latest version will cause errors as below when built in readthedocs. How can i fix it?

Running Sphinx v1.6.7
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 163, in __init__
    raise ConfigError(CONFIG_ERROR % traceback.format_exc())
ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 18, in <module>
    from recommonmark.parser import CommonMarkParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/src/recommonmark/recommonmark/parser.py", line 9, in <module>
    from CommonMark import Parser
ImportError: cannot import name Parser


Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 18, in <module>
    from recommonmark.parser import CommonMarkParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/fisco-bcos-doc-new/envs/latest/src/recommonmark/recommonmark/parser.py", line 9, in <module>
    from CommonMark import Parser
ImportError: cannot import name Parser
