### ISSUE TITLE
"NoneType object is not callable" when trying to link between documents

### ISSUE THREAD

**Issue by multimeric** [readthedocs/recommonmark#93]
I've noticed that adding a hyperlink between documents, when AutoStructify is enabled, causes the following error:
```
File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/states.py", line 135, in run_role
  content=content)
TypeError: 'NoneType' object is not callable
```

For a full example, clone this repo (https://github.com/TMiguelT/Sphinx-Bug-AutoStructify) and run
```bash
sphinx-build . $(mktemp -d)
```

The full error log is here: 
```Traceback (most recent call last):
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 329, in build_update
    'out of date' % len(to_build))
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 342, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 601, in update
    self._read_serial(docnames, self.app)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 621, in _read_serial
    self.read_doc(docname, app)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 758, in read_doc
    pub.publish()
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 325, in apply
    self.traverse(self.document)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 297, in traverse
    self.traverse(child)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 297, in traverse
    self.traverse(child)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 297, in traverse
    self.traverse(child)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 287, in traverse
    newnode = self.find_replace(c)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 267, in find_replace
    newnode = self.auto_doc_ref(node)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/transform.py", line 175, in auto_doc_ref
    return self.state_machine.run_role('doc', content=content)
  File "/home/michael/Programming/GenovicAnalysis/venv/local/lib/python2.7/site-packages/recommonmark/states.py", line 135, in run_role
    content=content)
TypeError: 'NoneType' object is not callable

**Comment by TMiguelT** [comment]
Notably, this works again when you add
```python
    app.add_config_value('recommonmark_config', {
        'enable_auto_doc_ref': False,
    }, True)
```

So it must be related to the `auto_doc_ref` feature.

**Comment by mapio** [comment]
Same here, unfortunately setting `enable_auto_doc_ref` of course disables the document linking (resulting in broken links).

**Comment by pfultz2** [comment]
On the README, it says that `enable_auto_doc_ref` is deprecated. This is because now links which are not explicit URLs, are treated as cross references with the [`:any:`](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-any) role.

**Comment by mazerte** [comment]
Hi, I have the exactly same issue when I use nested list of links

```
* [Page 1](page1/index.md)
    * [SubPage 1](page1/subpage1.md)
    * [SubPage 2](page1/subpage2.md)
* [Page 2](page2/index.md)
    * [SubPage 1](page2/subpage1.md)
```

If I switch to `enable_auto_doc_ref ` no more error but no more link.

It also works when the list is flat:
```
* [Page 1](page1/index.md)
* [SubPage 1](page1/subpage1.md)
* [SubPage 2](page1/subpage2.md)
* [Page 2](page2/index.md)
* [SubPage 1](page2/subpage1.md)
```

So I'm block can you help me ?
Thanks

**Comment by cas--** [comment]
The best workaround would seem to be installing latest code from the git repo: 

    pip install git+https://github.com/rtfd/recommonmark.git

To specify branch or commit see: https://stackoverflow.com/a/13754517/175584

----

Alternatively based on @mvancanneyt change, a hacky monkey patch can be applied to recommonmark 0.4 in the sphinx config by adding this near the top of `conf.py` :

```python
from recommonmark.states import DummyStateMachine
# Monkey patch to fix recommonmark 0.4 doc reference issues.
orig_run_role = DummyStateMachine.run_role
def run_role(self, name, options=None, content=None):
    if name == 'doc':
        name = 'any'
    return orig_run_role(self, name, options, content)
DummyStateMachine.run_role = run_role
```

----
@pfultz2 I was confused by this, however if you look at the PyPi release date it is 0.4 (Jan 2016) whereas the [deprecation change](8baf238562c2f7) occurred in Mar 2017. So for recommonmark 0.4 `enable_auto_doc_ref` is the only option. The project really needs to use tags to differentiate versions on rtfd.

**Comment by michaeldboyd** [comment]
Are there plans to incorporate this fix into the next release?

 I'm currently blocked by this issue as well. When I hard code the change like @mvancanneyt it works, but the hacky monkey patch that @cas-- offered hasn't worked for me yet - I'm adding the PatchDummyStateMachine to the top of my conf.py, but it's not catching the override when I build. 

Does anyone have any feedback on why it isn't working? My conf.py file is here: https://github.com/michaeldboyd/indy-sdk/blob/sphinx-docs-test/docs/conf.py

Thanks

**Comment by cas--** [comment]
My patch has to be applied after other recommonmark imports, otherwise it'll be reverted.

**Comment by michaeldboyd** [comment]
@cas-- Hmm, I've changed my [conf.py](https://github.com/michaeldboyd/indy-sdk/blob/sphinx-docs-test/docs/conf.py) so that your patch is applied after all the other imports. My sphinx build is still giving me this error below: 

```
reading sources... [ 29%] design/005-dkms/README
Exception occurred:
  File "/home/mdb/.local/lib/python3.6/site-packages/recommonmark/states.py", line 134, in run_role
    content=content)
TypeError: 'NoneType' object is not callable

```

Thank you for your help, do you have any other ideas why this might not be working?

**Comment by cas--** [comment]
Ah oops, it seems my refactor of the patch didn't work (along with not getting that error anymore didn't catch that) so try my original patch: 

```python
from recommonmark.states import DummyStateMachine
# Monkey patch to fix recommonmark 0.4 doc reference issues.
orig_run_role = DummyStateMachine.run_role
def run_role(self, name, options=None, content=None):
    if name == 'doc':
        name = 'any'
    return orig_run_role(self, name, options, content)
DummyStateMachine.run_role = run_role
```

**Comment by michaeldboyd** [comment]
Great! That works. Thank you for the help.

**Comment by michaeldboyd** [comment]
Are there plans to incorporate a fix for this in a future release?
